server:
  port: 8080

spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: nebula

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    properties:
      mail:
        debug: true
        smtp:
          auth: ${SMTP_AUTH:true}
          starttls:
            enable: ${SMTP_STARTTLS:true}
          ssl:
            trust: ${SMTP_SSL_TRUST:smtp.gmail.com}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 900000 # 15 minutes

# default from address
mail-defaults:
  from: ${MAIL_FROM}