server:
  port: 8080

spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: "MONGODB_URI"
      database: nebula
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER:${MAIL_USERNAME}}
    password: ${SMTP_PASS:${MAIL_PASSWORD}}
    properties:
      mail:
        debug: true
        smtp:
          auth: ${SMTP_AUTH:true}
          starttls:
            enable: ${SMTP_STARTTLS:true}
          ssl:
            trust: ${SMTP_SSL_TRUST:smtp.gmail.com}

app:
  jwt:
    # A standard 256-bit base64-encoded secret key for local fallback.
    secret: ${JWT_SECRET}
    expiration-ms: 86400000 # 24 hours (1 day)

# default from address (root-level env override)
mail-defaults:
  from: ${MAIL_FROM:navyaneelam115@gmail.com}
